import {
	collection,
	doc,
	getDocs,
	orderBy,
	query,
	setDoc,
	updateDoc,
	where,
} from "firebase/firestore";
import { getBook, type Book, type ISBN } from "./bookapi";
import { getPostFromId, type Post, type PostId } from "./postapi";
import { fuzzyQuery, type Nominal } from "./util";
import {
	browserLocalPersistence,
	createUserWithEmailAndPassword,
	deleteUser,
	EmailAuthProvider,
	getAuth,
	onAuthStateChanged,
	reauthenticateWithCredential,
	setPersistence,
	signInWithEmailAndPassword,
	signOut,
	updateEmail,
	updatePassword,
} from "firebase/auth";
import firebase from "./firebase";
import type { FileId } from "./storageapi";

export type UserId = Nominal<string, "user">;

export type User = {
	username: string;
	email: string;
	id: UserId;

	notifyingPosters: UserId[];

	// Profile
	displayName: string;
	banner: FileId;
	picture: FileId;
	bio: string;
	tags: string[];
	links: {}[];
	currentBook: ISBN | null;
	pronouns: string;
	showDeveloperBadge: boolean;
	showModeratorBadge: boolean;
	showPronounsOnProfile: boolean;
	showPronounsOnPosts: boolean;
	showNewbieBadge: boolean;
	showAuthorBadge: boolean;

	/** The timestamp, in epoch milliseconds, that this user's account was created. */
	birthmoment: number;

	views: PostId[];
	likes: PostId[];
	shares: PostId[];
	saved: PostId[];

	readingList: ISBN[];
	currentlyReading: ISBN[];

	following: UserId[];

	/** Whether the user has requested author verification. */
	requestedAuthorVerification: boolean;

	// Preferences
	darkMode: boolean;
	uiScale: number;
};

let { db } = firebase();

const auth = getAuth();
setPersistence(auth, browserLocalPersistence);

let currentUser: User | null = $state(null);

export function user(): User | null {
	return currentUser;
}

export function usernameErrors(username: string): string[] {
	let errors = [];
	if (username.length > 20) errors.push("Username can't be more than 30 characters");
	if (username.startsWith("-")) errors.push("Username can't start with a hyphen.");
	if (username.endsWith("-")) errors.push("Username can'end with a hyphen.");
	if (!/^[\w\-]*$/.test(username))
		errors.push("Username can only contain letters, numbers, underscores, and hyphens");
	if (/^\d+$/.test(username)) errors.push("Username cannot be only numbers");
	if (/^\-+$/.test(username)) errors.push("Username cannot be only hyphens");
	if (/^\_+$/.test(username)) errors.push("Username cannot be only underscores");
	return errors;
}

export let resolveUser: (user: User) => void;

/**
 * A promise that resolves when the user has loaded. After this promise is resolved, `user()` can
 * be used safely and will return a non-null value. For convenience, the promise returns the user.
 */
export let awaitUser: Promise<User> = new Promise(resolve => {
	resolveUser = resolve;
});

/**
 * Returns a user's "favorite book" which is defined as the book that
 * they have rated the highest. if the user has not rated any books, this
 * returns `null`. If the user has rated at least one book, this is guaranteed
 * to return a non-null value.
 *
 * # Parameters
 *
 * - `user` - The user to get the highest rated book of
 *
 * # Returns
 *
 * The highest rated book from the given user, or `null` if the user hasn't
 * rated any books.
 */
export async function getFavoriteBook(user: User): Promise<Book | null> {
	let posts = (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "==", user.id),
				where("type", "==", "rating"),
			),
		)
	).docs.map(doc => doc.data()) as Post[];
	let books = posts.toSorted((a, b) => b.rating! - a.rating!).map(post => post.books[0]);
	return books.length > 0 ? await getBook(books[0] as ISBN) : null;
}

export async function getFollowers(user: User): Promise<User[]> {
	const followers: User[] = [];
	(
		await getDocs(query(collection(db, "users"), where("following", "array-contains", user.id)))
	).forEach(doc => followers.push(doc.data() as User));

	return followers;
}

/**
 * Returns the `User` object associated with the given `UserId`. The id is an
 * underlying internal persistent string generated by Firebase, not a human-readable
 * string. To get a user by their username (@), use `getUserFromUsername()`
 *
 * @param id The id of the user to get
 *
 * @returns The user with the given id
 */
export async function getUserFromId(id: UserId): Promise<User> {
	let internalUser = (
		await getDocs(query(collection(db, "users"), where("id", "==", id)))
	).docs[0].data() as User;
	return internalUser;
}

export async function internalUserToUser(user: User): Promise<User> {
	return user;
}

export async function getUserFromUsername(username: string): Promise<User> {
	let user = (
		await getDocs(query(collection(db, "users"), where("username", "==", username)))
	).docs[0].data() as User;
	return user;
}

export async function getNumberOfBooksRead(user: User): Promise<number> {
	return (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "==", user.id),
				where("type", "==", "rating"),
			),
		)
	).docs.length;
}

export async function getUserPosts(user: User): Promise<Post[]> {
	let internalPosts = (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "==", user.id),
				orderBy("timestamp", "desc"),
			),
		)
	).docs.map(doc => doc.data()) as Post[];
	return internalPosts;
}

export async function searchUsers(searchTerm: string): Promise<User[]> {
	if (searchTerm === "") return Promise.resolve([]);
	if (searchTerm.startsWith("@")) {
		const docs = (
			await getDocs(
				query(collection(db, "users"), where("username", "==", searchTerm.substring(1))),
			)
		).docs;
		return docs.length > 0 ? [docs[0].data() as User] : [];
	}
	return fuzzyQuery(searchTerm, "displayName", "users");
}

export const defaultPreferences = {
	darkMode: true,
	uiScale: 1,
} as const satisfies Preferences;

type Preferences = {
	darkMode: boolean;
	uiScale: number;
};

export type Preference = keyof Preferences;
export type PreferenceValue<T extends Preference> = Preferences[T];

export function getPreference<Name extends Preference>(name: Name): PreferenceValue<Name> {
	if (user()) return user()![name];

	const fromStorage = localStorage.getItem(`preference-${name}`);
	if (fromStorage) return JSON.parse(fromStorage);

	const preference = defaultPreferences[name];
	localStorage.setItem(`preference-${name}`, JSON.stringify(preference));

	return preference;
}

export async function setPreference<Name extends Preference>(
	name: Name,
	value: PreferenceValue<Name>,
): Promise<void> {
	localStorage.setItem(`preference-${name}`, JSON.stringify(value));
	if (user()) await updateUser({ [name]: value });
}

export async function getMentions(): Promise<Post[]> {
	const username = user()!.username;
	const allPosts = (
		await getDocs(query(collection(db, "posts"), orderBy("timestamp", "desc")))
	).docs.map(doc => doc.data() as Post);
	const mentions = allPosts.filter(post => new RegExp(`@${username}\\b`).test(post.body));
	return mentions;
}

export async function getRepliesToUser(user: User): Promise<Post[]> {
	const allPosts = (
		await getDocs(
			query(
				collection(db, "posts"),
				where("type", "==", "reply"),
				orderBy("timestamp", "desc"),
			),
		)
	).docs.map(doc => doc.data() as Post);

	const repliesToUser = allPosts.filter(async post => {
		const parent = (await getPostFromId(post.parent))!;
		return parent.poster === user.id;
	});

	return repliesToUser;
}

export async function getFollowingPosts(): Promise<Post[]> {
	const allPosts = (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "in", user()!.following),
				orderBy("timestamp", "desc"),
			),
		)
	).docs.map(doc => doc.data() as Post);

	return allPosts;
}

export async function getNotifyingPosts(): Promise<Post[]> {
	const allPosts = (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "in", user()!.notifyingPosters),
				orderBy("timestamp", "desc"),
			),
		)
	).docs.map(doc => doc.data() as Post);

	return allPosts;
}

/**
 * Returns a list of strings, each of which representing an error in the validity of the
 * given password, such as "Must contain at least 1 number". If the password is a valid
 * password, an empty list is returned.
 */
export function passwordErrors(password: string): string[] {
	if (password === "") return [];
	let errors = [];
	if (!/\d/.test(password)) errors.push("Must contain at least 1 number");
	if (!/[a-z]/.test(password)) errors.push("Must contain at least 1 lowercase letter");
	if (!/[A-Z]/.test(password)) errors.push("Must contain at least 1 uppercase letter");
	if (!/[\$_=\+\*!@#%\^&\|\\\/\(\)\[\]\{\}<>\?:;'"`~\-]/.test(password))
		errors.push("Must contain at least 1 symbol");
	if (password.length < 8) errors.push("Must be at least 8 characters");
	return errors;
}

export async function usernameIsTaken(username: string): Promise<boolean> {
	return (
		(await getDocs(query(collection(db, "users"), where("username", "==", username)))).docs
			.length > 0
	);
}

export async function emailIsTaken(email: string): Promise<boolean> {
	return (
		(await getDocs(query(collection(db, "users"), where("email", "==", email)))).docs.length > 0
	);
}

onAuthStateChanged(auth, async user => {
	// Logged in
	if (user) {
		currentUser = await internalUserToUser(
			(
				await getDocs(query(collection(db, "users"), where("id", "==", user.uid)))
			).docs[0].data() as User,
		);
		resolveUser(currentUser);
	}

	// logged out
	else {
	}
});

export async function logOut(): Promise<unknown | null> {
	try {
		await signOut(auth);
		return null;
	} catch (error) {
		console.log(error);
		return error;
	}
}

export async function updateUser(userInfo: Partial<User>) {
	Object.entries(userInfo).forEach(([key, value]) => ((currentUser as any)[key] = value));
	await updateDoc(doc(db, "users", user()!.id), userInfo);
}

export async function signUp(
	email: string,
	password: string,
	username: string,
): Promise<unknown | null> {
	try {
		const darkMode = getPreference("darkMode");
		const uiScale = getPreference("uiScale");
		let userInfo = await createUserWithEmailAndPassword(auth, email, password);
		let user: User = {
			displayName: username,
			email,
			username,
			picture:
				"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToiRnzzyrDtkmRzlAvPPbh77E-Mvsk3brlxQ&s" as FileId,
			bio: "",
			pronouns: "",
			likes: [],
			id: userInfo.user.uid as UserId,
			banner: "https://i0.wp.com/www.lifecaretechnology.com/wp-content/uploads/2018/12/default-banner.jpg?ssl=1" as FileId,
			tags: [],
			showDeveloperBadge: true,
			showModeratorBadge: true,
			showPronounsOnProfile: true,
			showPronounsOnPosts: true,
			showNewbieBadge: true,
			showAuthorBadge: true,
			links: [],
			currentBook: null,
			readingList: [],
			following: [],
			darkMode,
			uiScale,
			views: [],
			shares: [],
			saved: [],
			notifyingPosters: [],
			currentlyReading: [],
			requestedAuthorVerification: false,
			birthmoment: Date.now(),
		};
		await setDoc(doc(db, "users", user.id), user);
		return null;
	} catch (error) {
		console.log(error);
		return error;
	}
}

export async function logIn(email: string, password: string): Promise<{ code: string } | null> {
	try {
		await signInWithEmailAndPassword(auth, email, password);
		return null;
	} catch (error) {
		console.log(error);
		return error as { code: string };
	}
}

export async function getUserReplies(user: User): Promise<Post[]> {
	return (
		await getDocs(
			query(
				collection(db, "posts"),
				where("poster", "==", user.id),
				where("type", "==", "reply"),
				orderBy("timestamp", "desc"),
			),
		)
	).docs.map(doc => doc.data() as Post);
}

export async function changePassword(oldPassword: string, newPassword: string) {
	const credential = EmailAuthProvider.credential(auth.currentUser!.email!, oldPassword);
	await reauthenticateWithCredential(auth.currentUser!, credential);
	await updatePassword(auth.currentUser!, newPassword);
}

export async function changeEmail(email: string, password: string) {
	const credential = EmailAuthProvider.credential(auth.currentUser!.email!, password);
	await reauthenticateWithCredential(auth.currentUser!, credential);
	await updateEmail(auth.currentUser!, email);
	await updateUser({ email });
}

export async function deleteAccount(password: string) {
	const credential = EmailAuthProvider.credential(auth.currentUser!.email!, password);
	await reauthenticateWithCredential(auth.currentUser!, credential);
	await deleteUser(auth.currentUser!);
}
